# Generated by Django 4.0 on 2022-01-01 20:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_article_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='mesure',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='core.mesure'),
        ),
    ]
