# Generated by Django 4.0 on 2022-01-03 09:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_alter_client_mesure'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='client',
            name='mesure',
        ),
        migrations.AddField(
            model_name='mesure',
            name='client',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, to='core.client'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='category',
            name='name',
            field=models.CharField(blank=True, max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name='client',
            name='name',
            field=models.CharField(blank=True, max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name='modele',
            name='name',
            field=models.CharField(blank=True, max_length=255, unique=True),
        ),
    ]
