# Generated by Django 3.2.9 on 2022-01-21 02:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_auto_20220114_1536'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='status',
            field=models.CharField(choices=[('En Vente', 'En Vente'), ('Vendu', 'Vendu')], default='En vente', max_length=255),
        ),
        migrations.AlterField(
            model_name='order',
            name='state',
            field=models.CharField(choices=[('EC', 'En Conception'), ('T', 'Terminée'), ('C', 'Commandée'), ('M', 'Attente de Matériel'), ('A', 'Annulée')], default=('C', 'Commandée'), max_length=100),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='echantillon',
            field=models.ImageField(blank=True, null=True, upload_to='images/echantillons'),
        ),
    ]
